[dev]
  framework = "hugo"
  targetPort = 3000

[build]
  publish = "public"
  command = """\
  curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  export PATH=/opt/build/repo/dart-sass:$PATH && \
  hugo --gc --minify && \
  cp _redirects public/_redirects \
  """

  [build.environment]
    HUGO_VERSION = "0.130.0"
    DART_SASS_VERSION = "1.77.8"
    # Cache processed images between builds
    HUGO_RESOURCEDIR = "/opt/build/cache/hugo_cache"

[context.production.environment]
  HUGO_ENV           = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

  [context.split1.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
  command = """\
  curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
  export PATH=/opt/build/repo/dart-sass:$PATH && \
  hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && \
  cp _redirects public/_redirects \
  """

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

# Netlify Build Plugin for Hugo caching
[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
