local_backend: true

backend:
  name: git-gateway
  branch: decap-cms-integration

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "content/blog/posts"
    path: "{{slug}}/index"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Short Description", name: "description", widget: "text"}

      - label: "Featured posts"
        name: "featured"
        widget: "object"
        summary: '{{fields.name}}: {{fields.birthdate}}'
        fields:
          - {label: "Promote", name: "promote", widget: "boolean", required: false, default: false}
          - {label: "url", name: "url", widget: "string", required: false}
          - {label: "Top", name: "top", widget: "boolean", required: false, default: false}

      - label: "Questionary"
        name: "questionary"
        widget: "list"
        summary: '{{fields.quote}} - {{fields.question.name}}'
        fields:
          - {label: Question, name: question, widget: string, required: false, default: "Everything is awesome!"}
          - {label: Answer, name: answer, widget: string, required: false, default: "Everything is awesome!"}

      # Authors list from "content/authors" folder
      - label: Authors
        name: authors
        widget: relation
        collection: "authors"
        required: false
        multiple: true
        search_fields: ["name"]
        value_field: "name"
        display_fields: ["name"]

      - label: "Categories"
        name: "categories"
        widget: "relation"
        file: "categories"
        required: false
        multiple: true
        collection: "taxonomy"
        search_fields: ["categories.*.name"]
        display_fields: ["categories.*.name"]
        value_field: "categories.*.name"

      - label: "Industries"
        name: "industries"
        widget: "relation"
        file: "industries"
        required: false
        multiple: true
        collection: "taxonomy"
        search_fields: ["industries.*.name"]
        display_fields: ["industries.*.name"]
        value_field: "industries.*.name"

  - label: "Authors"
    label_singular: "Author"
    identifier_field: name
    name: "authors"
    folder: "content/authors"
    path: "{{slug}}/index"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Member Since", name: "memberSince", widget: "datetime"}
      - {label: "Avatar", name: "avatar", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Short Description", name: "shortDescription", widget: "text"}
      - {label: "Position", name: "position", widget: "string"}

  - label: "Taxonomy"
    name: "taxonomy"
    delete: false
    files:
      - file: 'data/categories.json'
        label: 'Categories'
        name: 'categories'
        editor:
          preview: false
        fields:
          - label: 'Categories'
            label_singular: "Category"
            name: 'categories'
            widget: 'list'
            allow_add: true
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
      - file: 'data/industries.json'
        label: 'Industries'
        name: 'industries'
        editor:
          preview: false
        fields:
          - label: 'industries'
            label_singular: "Industry"
            name: 'industries'
            expanded: false
            widget: 'list'
            allow_add: true
            fields:
              - { label: 'Name', name: 'name', widget: 'string', expanded: false}
