name: Build and Deploy to Netlify

on:
  push:
    branches:
      - main
      - master
      - dev  # Add your production branches

permissions:
  contents: read  # Only read access needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.130.0'
          extended: true

      - name: Install Dart Sass
        run: |
          curl -LJO https://github.com/sass/dart-sass/releases/download/1.77.8/dart-sass-1.77.8-linux-x64.tar.gz
          tar -xf dart-sass-1.77.8-linux-x64.tar.gz
          rm dart-sass-1.77.8-linux-x64.tar.gz
          echo "$GITHUB_WORKSPACE/dart-sass" >> $GITHUB_PATH

      - name: Cache Hugo resources
        uses: actions/cache@v3
        with:
          path: resources/_gen
          key: ${{ runner.os }}-hugo-${{ hashFiles('content/**/*.jpg', 'content/**/*.jpeg', 'content/**/*.png', 'content/**/*.gif', 'content/**/*.webp') }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Build Hugo site
        env:
          HUGO_ENV: production
        run: |
          echo "🚀 Building site..."
          hugo --gc --minify
          cp _redirects public/_redirects || true
          echo "✅ Build complete! Size: $(du -sh public | cut -f1)"

      # Option A: Deploy using Netlify CLI
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install -g netlify-cli

          if [ "${{ github.ref }}" = "refs/heads/main" ] || [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "🎯 Deploying to production..."
            netlify deploy --prod --dir=public --message="Deploy from GitHub Actions: ${{ github.sha }}"
          else
            echo "🔍 Deploying preview..."
            netlify deploy --dir=public --message="Preview deploy: ${{ github.ref_name }}"
          fi

      # Option B: Deploy using netlify-action (alternative)
      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v2.1
      #   with:
      #     publish-dir: './public'
      #     production-deploy: ${{ github.ref == 'refs/heads/main' }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     deploy-message: "Deploy from GitHub Actions"
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}